[package]
name = "flux-errors"
version = "0.1.0"

edition.workspace = true

[lib]
doctest = false
test = false

[dependencies]
flux-common.workspace = true

[package.metadata.rust-analyzer]
rustc_private = true

[lints]
workspace = true
